#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jun 15 22:32:23 2024

@author: J.Cabrera-Moreno
Postdoctoral Fellow
Evolutionary Cognition Group
Institute of Evolutionary Anthropology
University of Zürich

Description:
    The following code serves a satelite code for handling
    the creation of a loging file and the loging of the data
    generated by clientPump.py
"""

import os
import socket
import sys
import csv
from datetime import datetime

class FileManager:
    def __init__(self, directory):
        self.directory = os.path.expanduser(directory)
        self.ensure_directory_exists()
        self.machineID = socket.gethostname()

    def ensure_directory_exists(self):
        if not os.path.exists(self.directory):
            os.makedirs(self.directory)

    def get_current_datetime(self, filename):
        # Get the current date and time
        now = datetime.now()
        
        # Format the date and time in the specified format
        if not filename:
            formatted_datetime = now.strftime('%Y%m%d%H%M%S%f')[:-2]
        else:
            formatted_datetime = now.strftime('%Y%m%d%H%M%S')
        
        return formatted_datetime

    def create_file(self, columnNames):
        # Get the current date-time filename
        formatted_datetime = self.get_current_datetime(True)
        
        # Append '.txt' to the formatted date and time
        filename = f"{formatted_datetime}.txt"
        
        # Create the full file path
        file_path = os.path.join(self.directory, filename)
        
        # Create and open the file
        with open(file_path, 'w') as file:
            file.write(f"MachineID: {self.machineID}\n")
            file.write(columnNames)
        
        return file_path

    def log_to_file(self, file_path, log):
        # Append a new line to the existing file
        with open(file_path, 'a') as file:
            file.write(log + '\n')
            
    def get_animal_name_from_file(self, filename, animal_tag):
        """
        Search for the animal name based on its tag in a CSV file.
        :return: Name of the animal or None if not found.
        """
        # Create the full file path
        file_path = os.path.join(self.directory, filename)
        
        try:
            with open(file_path, mode='r') as file:
                reader = csv.reader(file)
                for row in reader:
                    if len(row) >= 2 and row[1].strip() == str(animal_tag):
                        return row[0].strip()
        except Exception as e:
                print(f"Error reading file: {e}")
        return None

if __name__ == "__main__":
    # Example usage
    directory = '/home/pi/Documents/Data'  # Replace with pertinent directory
    file_manager = FileManager(directory)
    
    # Create a new file
    created_file_path = file_manager.create_file()
    print(f"File created: {created_file_path}")
    
    # Append a new line to the created file
    file_manager.log_to_file(created_file_path, "")
    print(f"New line appended to: {created_file_path}")
